function [value, isterminal, direction] = switch_func( t, y, l, M, psi0 )
    moe = 10e-6;    
    value = [int8((- abs(y(3).*(l + y(1)) ./ y(2) + y(4))) ./ (2 .* psi0) > moe); ...
        int8(y(2) - M > moe);...
        1;...
        1;...
        int8(y(3).^2 + y(4).^2 > moe)...
    ];
    isterminal = [1, 1, 1, 1, 1];
    direction = 0;


end

